//
//  ShiDianUMHeader.h
//  ShiDianUM
//
//  Created by Charlin on 2016/11/3.
//  Copyright © 2016年 Charlin. All rights reserved.
//

#ifndef ShiDianUMHeader_h
#define ShiDianUMHeader_h

#import "ShiDianUM.h"
#import "ShiDianUM+Register.h"
#import "ShiDianUM+Login.h"

#endif 
/* ShiDianUMHeader_h */


/*
 *  集成步骤
 1.下载并导入SocialLibraries，UMSocialSDK
 2.依次引入一下框架：
     libc++.tbd,
     libz.tbd,
     libsqlite3.tbd,
     ImageIO.framework,
     CoreTelephony.framework,
     SystemConfiguration.framework
 3.添加URL Types: http://dev.umeng.com/social/ios/quick-integration
 4.适配iOS9/10系统，在info.plist:
     <key>CFBundleURLTypes</key>
        <array>
     <dict>
     <key>CFBundleTypeRole</key>
     <string>Editor</string>
     <key>CFBundleURLSchemes</key>
     <array>
     <string>wxa96be782c0c6c46e</string>
     </array>
     </dict>
     <dict>
     <key>CFBundleTypeRole</key>
     <string>Editor</string>
     <key>CFBundleURLSchemes</key>
     <array>
     <string>tencent1104942784</string>
     </array>
     </dict>
     <dict>
     <key>CFBundleTypeRole</key>
     <string>Editor</string>
     <key>CFBundleURLSchemes</key>
     <array>
     <string>QQ41dc16c0</string>
     </array>
     </dict>
        </array>
        <key>CFBundleVersion</key>
        <string>1</string>
        <key>LSApplicationQueriesSchemes</key>
        <array>
     <string>wechat</string>
     <string>weixin</string>
     <string>sinaweibohd</string>
     <string>sinaweibo</string>
     <string>sinaweibosso</string>
     <string>weibosdk</string>
     <string>weibosdk2.5</string>
     <string>mqqapi</string>
     <string>mqq</string>
     <string>mqqOpensdkSSoLogin</string>
     <string>mqqconnect</string>
     <string>mqqopensdkdataline</string>
     <string>mqqopensdkgrouptribeshare</string>
     <string>mqqopensdkfriend</string>
     <string>mqqopensdkapi</string>
     <string>mqqopensdkapiV2</string>
     <string>mqqopensdkapiV3</string>
     <string>mqqopensdkapiV4</string>
     <string>mqzoneopensdk</string>
     <string>wtloginmqq</string>
     <string>wtloginmqq2</string>
     <string>mqqwpa</string>
     <string>mqzone</string>
     <string>mqzonev2</string>
     <string>mqzoneshare</string>
     <string>wtloginqzone</string>
     <string>mqzonewx</string>
     <string>mqzoneopensdkapiV2</string>
     <string>mqzoneopensdkapi19</string>
     <string>mqzoneopensdkapi</string>
     <string>mqqbrowser</string>
     <string>mttbrowser</string>
     <string>alipay</string>
     <string>alipayshare</string>
     <string>renrenios</string>
     <string>renrenapi</string>
     <string>renren</string>
     <string>renreniphone</string>
     <string>laiwangsso</string>
     <string>yixin</string>
     <string>yixinopenapi</string>
     <string>instagram</string>
     <string>whatsapp</string>
     <string>line</string>
     <string>fbapi</string>
     <string>fb-messenger-api</string>
     <string>fbauth2</string>
     <string>fbshareextension</string>
        </array>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>NSAppTransportSecurity</key>
        <dict>
     <key>NSAllowsArbitraryLoads</key>
     <true/>
     <key>NSExceptionDomains</key>
     <dict>
     <key>akamaihd.net</key>
     <dict>
     <key>NSExceptionRequiresForwardSecrecy</key>
     <false/>
     <key>NSIncludesSubdomains</key>
     <true/>
     </dict>
     <key>facebook.com</key>
     <dict>
     <key>NSExceptionRequiresForwardSecrecy</key>
     <false/>
     <key>NSIncludesSubdomains</key>
     <true/>
     </dict>
     <key>fbcdn.net</key>
     <dict>
     <key>NSExceptionRequiresForwardSecrecy</key>
     <false/>
     <key>NSIncludesSubdomains</key>
     <true/>
     </dict>
     <key>linkedin.com</key>
     <dict>
     <key>NSExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSExceptionRequiresForwardSecrecy</key>
     <false/>
     <key>NSIncludesSubdomains</key>
     <true/>
     </dict>
     <key>log.umsns.com</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSTemporaryExceptionMinimumTLSVersion</key>
     <string>TLSv1.1</string>
     </dict>
     <key>qq.com</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>renren.com</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>sina.cn</key>
     <dict>
     <key>NSExceptionMinimumTLSVersion</key>
     <string>TLSv1.0</string>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>sina.com.cn</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>sinaimg.cn</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>sinajs.cn</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>sns.whalecloud.com</key>
     <dict>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSTemporaryExceptionMinimumTLSVersion</key>
     <string>TLSv1.1</string>
     </dict>
     <key>twitter.com</key>
     <dict>
     <key>NSExceptionRequiresForwardSecrecy</key>
     <false/>
     <key>NSIncludesSubdomains</key>
     <true/>
     </dict>
     <key>weibo.cn</key>
     <dict>
     <key>NSExceptionMinimumTLSVersion</key>
     <string>TLSv1.0</string>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     <key>weibo.com</key>
     <dict>
     <key>NSExceptionMinimumTLSVersion</key>
     <string>TLSv1.0</string>
     <key>NSIncludesSubdomains</key>
     <true/>
     <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
     <true/>
     <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
     <false/>
     </dict>
     </dict>
        </dict>
        <key>UILaunchStoryboardName</key>
        <string>LaunchScreen</string>
        <key>UIMainStoryboardFile</key>
        <string>Main</string>
        <key>UIRequiredDeviceCapabilities</key>
        <array>
     <string>armv7</string>
        </array>
        <key>UISupportedInterfaceOrientations</key>
        <array>
     <string>UIInterfaceOrientationPortrait</string>
     <string>UIInterfaceOrientationLandscapeLeft</string>
     <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
 */
